---
- name: Add NodeSource repository key
  apt_key:
    id: "68576280"
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    state: present

- name: Add NodeSource 6.x repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_6.x trusty main'
    state: present

- name: Update package list
  apt:
    update_cache: yes

- name: Install nodejs
  apt:
    name: nodejs
    state: present

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - npm@4.5.0
    - bower
    - grunt-cli
    - yo
    - generator-karma
    - generator-angular

- name: Install local npm packages
  npm:
    path: "{{ frontend_root_dir }}"
    state: present

- name: Install bower dependencies
  bower:
    path: "{{ frontend_root_dir }}"
