---
- name: Add PostgreSQL repository key
  apt_key:
    id: "ACCC4CF8"
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
    state: present

- name: Update package list
  apt:
    update_cache: yes

- name: Install PostgreSQL 9.6
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-9.6
    - libpq-dev
    - python-psycopg2

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create database "{{ db.name }}"
  become_user: postgres
  postgresql_db:
    name: "{{ db.name }}"

- name: Create database user "{{ db.user }}" iwth password "{{ db.password }}"
  become_user: postgres
  postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.user }}"
    password: "{{ db.password }}"
    priv: ALL
