---
- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install core packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - vim
    - apt-transport-https
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - unzip
    - gettext
    - libssl-dev
    - git

- name: Add venv activation to .profile file
  blockinfile:
    dest: "{{ default_user_home_dir }}/.profile"
    block: |
      source {{ backend.env_root_dir }}/bin/activate
      cd {{ project_src_dir }}
    marker: "### {mark} VENV ACTIVATION ###"